spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?sslmode=require
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.devtools.add-properties=true
logging.level.web=DEBUG

# --- Supabase Config ---
supabase.url=${SUPABASE_URL:https://your-project.supabase.co}
supabase.anon.key=${SUPABASE_ANON_KEY:your-anon-key}
